import '@/styles/globals.css'
import {Noto_Sans_JP, M_PLUS_1} from 'next/font/google'
import {ReactNode} from 'react'
import Header from '@/components/Header/Header'

const notojp = Noto_Sans_JP({
    weight: ['400', '500', '900'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: ReactNode
}) {
    return (
        <html lang="ja">
        <body className={`${notojp.className}`}>
        <Header/>
        {children}
        </body>
        </html>
    )
}
